import { PGlite } from "@electric-sql/pglite";
import fs from "fs";
import { beforeAll, describe, expect, it } from "vitest";
import {
  serializeBigIntAndDates,
  type DomainAddress,
  type DomainOrder,
  type DomainSellerOrder,
} from "../types";

describe("Real PostgreSQL Database Engine Persistence Tests", () => {
  let pglite: PGlite;

  beforeAll(async () => {
    // Spin up real embedded PostgreSQL WebAssembly engine
    pglite = new PGlite();

    // Read and execute the exact versioned SQL migration generated by Prisma
    const migrationSql = fs.readFileSync(
      "prisma/migrations/20250330000000_init/migration.sql",
      "utf-8"
    );
    await pglite.exec(migrationSql);
  });

  it("executes initial PostgreSQL schema migration and creates all required tables", async () => {
    const res = await pglite.query<{ table_name: string }>(
      "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;"
    );
    const tableNames = res.rows.map((r) => r.table_name);

    expect(tableNames).toContain("users");
    expect(tableNames).toContain("sellers");
    expect(tableNames).toContain("products");
    expect(tableNames).toContain("product_variants");
    expect(tableNames).toContain("inventories");
    expect(tableNames).toContain("orders");
    expect(tableNames).toContain("seller_orders");
    expect(tableNames).toContain("order_items");
    expect(tableNames).toContain("addresses");
    expect(tableNames).toContain("customers");
  });

  it("stores monetary amounts as integer BIGINT paise in real PostgreSQL tables", async () => {
    const userId = "10000000-0000-0000-0000-000000000001";
    const sellerId = "40000000-0000-0000-0000-000000000001";

    await pglite.query("INSERT INTO users (id, email, role, updated_at) VALUES ($1, $2, $3, NOW());", [
      userId,
      "test.seller@karigar.in",
      "ARTISAN_SELLER",
    ]);

    await pglite.query(
      `INSERT INTO sellers (id, user_id, legal_name, trade_name, pan, bank_details, verification_status, commission_rate_percentage)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8);`,
      [
        sellerId,
        userId,
        "Ansari Silk Weavers Pvt Ltd",
        "Ansari Silk",
        "AAAAA0000A",
        JSON.stringify({ bankName: "SBI", accountNumber: "12345" }),
        "VERIFIED",
        15.0,
      ]
    );

    // Verify raw query row
    const res = await pglite.query<{ trade_name: string; commission_rate_percentage: string }>(
      "SELECT trade_name, commission_rate_percentage FROM sellers WHERE id = $1;",
      [sellerId]
    );

    expect(res.rows[0].trade_name).toBe("Ansari Silk");
    expect(Number(res.rows[0].commission_rate_percentage)).toBe(15.0);
  });

  it("enforces foreign key constraints and prevents orphaned product variants", async () => {
    const orphanVariantId = "90000000-0000-0000-0000-000000000001";
    const invalidProductId = "non-existent-product";

    // Insertion of variant referencing non-existent product MUST fail with foreign key violation
    await expect(
      pglite.query(
        `INSERT INTO product_variants (id, product_id, sku, attributes) VALUES ($1, $2, $3, $4);`,
        [orphanVariantId, invalidProductId, "SKU-INVALID", JSON.stringify({ size: "M" })]
      )
    ).rejects.toThrow();
  });

  it("serializes BigInt paise and Date objects for REST API JSON responses without errors", () => {
    const address: DomainAddress = {
      id: "addr-1",
      customerId: "cust-1",
      recipientName: "Ananya Roy",
      addressLine1: "42 Golf Links",
      city: "New Delhi",
      state: "Delhi",
      postalCode: "110003",
      country: "IN",
      phone: "+919876543210",
    };

    const sellerOrderA: DomainSellerOrder = {
      id: "so-a",
      orderId: "order-90210",
      sellerId: "seller-a",
      sellerOrderNumber: "K-90210-A",
      status: "IN_CRAFTING",
      subtotalPaise: 2690000n, // ₹26,900
      commissionPaise: 403500n, // ₹4,035
      taxPaise: 0n,
      sellerPayoutPaise: 2286500n, // ₹22,865
      createdAt: new Date("2025-03-30T10:00:00Z"),
      items: [
        {
          id: "item-1",
          sellerOrderId: "so-a",
          productId: "banarasi-silk-stole",
          variantId: "var-1",
          quantity: 1,
          unitPricePaise: 2690000n,
          lineSubtotalPaise: 2690000n,
          productNameSnapshot: "Banarasi Silk Stole",
          variantAttributesSnapshot: { size: "Standard" },
          sellerNameSnapshot: "Ansari Silk Weavers",
        },
      ],
    };

    const topOrder: DomainOrder = {
      id: "order-90210",
      orderNumber: "K-90210",
      customerId: "cust-1",
      status: "PAID",
      subtotalPaise: 2690000n,
      taxPaise: 0n,
      shippingPaise: 0n,
      totalPaise: 2690000n,
      shippingAddress: address,
      createdAt: new Date("2025-03-30T10:00:00Z"),
      sellerOrders: [sellerOrderA],
    };

    // Serialize domain entity for REST response
    const restPayload = serializeBigIntAndDates(topOrder) as Record<string, unknown>;

    expect(restPayload.subtotalPaise).toBe("2690000");
    expect(restPayload.totalPaise).toBe("2690000");

    const serializedSellerOrder = (restPayload.sellerOrders as Record<string, unknown>[])[0];
    expect(serializedSellerOrder.commissionPaise).toBe("403500");
    expect(serializedSellerOrder.sellerPayoutPaise).toBe("2286500");
    expect(serializedSellerOrder.createdAt).toBe("2025-03-30T10:00:00.000Z");

    // Can be safely formatted with JSON.stringify without throwing TypeError
    const jsonString = JSON.stringify(restPayload);
    expect(jsonString).toContain('"subtotalPaise":"2690000"');
  });
});
